/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mailbox.h"

bool_t
xdr_str (XDR *xdrs, str *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_messages (XDR *xdrs, messages *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (str), (xdrproc_t) xdr_str))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_str (xdrs, &objp->user))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->msgid))
		 return FALSE;
	 if (!xdr_str (xdrs, &objp->msg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_usermsgid (XDR *xdrs, usermsgid *objp)
{
	register int32_t *buf;

	 if (!xdr_str (xdrs, &objp->user))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->msgid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listmessages (XDR *xdrs, listmessages *objp)
{
	register int32_t *buf;

	 if (!xdr_messages (xdrs, &objp->list))
		 return FALSE;
	return TRUE;
}
